// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// nco //
// --- //

#define nco_wrap_target 0
#define nco_wrap 3
#define nco_pio_version 1

static const uint16_t nco_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0                    
    0xe001, //  1: set    pins, 1                    
    0xe003, //  2: set    pins, 3                    
    0xe002, //  3: set    pins, 2                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program nco_program = {
    .instructions = nco_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = 1,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config nco_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + nco_wrap_target, offset + nco_wrap);
    return c;
}

static inline void nco_program_init(PIO pio, uint sm, uint offset) {
    pio_sm_config c = nco_program_get_default_config(offset);
    // Map the state machine's OUT pin group to one pin, namely the `pin`
    // parameter to this function.
    sm_config_set_set_pins(&c, 0, 2);
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, 0);
    pio_gpio_init(pio, 1);
    gpio_set_drive_strength(0, GPIO_DRIVE_STRENGTH_2MA);
    gpio_set_drive_strength(1, GPIO_DRIVE_STRENGTH_2MA);
    gpio_set_slew_rate(0, GPIO_SLEW_RATE_SLOW);
    gpio_set_slew_rate(1, GPIO_SLEW_RATE_SLOW);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, 0, 2, true);
    //set pio divider
    sm_config_set_clkdiv(&c, 1);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);
    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif

